---
- hosts: w
  become: true
  tasks:
          - name:  install java repo
            apt_repository: repo=ppa:webupd8team/java state=present
          - name: accept java license
            debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
          - name:  install java repo
            apt: name=oracle-java8-installer state=present update_cache=yes
