
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/messages
      - /var/log/cloud-init.log
    encoding: utf-8

output.logstash:
  hosts: ["logstash:5044"]
